# -*- coding: utf-8 -*-
"""MANOVA Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzCar4PAt7if28Ib8sEWH-yGooKiO-4i
"""

import pandas as pd
from statsmodels.multivariate.manova import MANOVA

# Uploading and Importing the "iris.csv" file
df = pd.read_csv('iris.csv', index_col=0)
df.columns = df.columns.str.replace(".","_")
df.head()

# Printing the imported data set
print("=================Data Set===================")
print(df)

# Implementing Formula
maov = MANOVA.from_formula('Sepal_Length + Sepal_Width + \
                            Petal_Length + Petal_Width  ~ Species', data=df)

print("================MANOVA Test Result==============")
print(maov.mv_test())