# -*- coding: utf-8 -*-
"""8A Positive Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11kAdUULLsyshb91wOWX868LRdMxlukKd
"""

# Importing Libraries
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

np.random.seed(1)

# 1000 random integer between 0 to 50
x = np.random.randint(0,50,1000)

# Postive Correlation with some noise
y = x + np.random.normal(0,10,1000)

np.corrcoef(x,y)

# Matplotlib in line
matplotlib.style.use('ggplot')

plt.scatter(x,y)
plt.show()