# -*- coding: utf-8 -*-
"""8B Negative Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F01dQm9deudJ8oARDRIRRjaO_IeQ_I-e
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

np.random.seed(1);

# 1000 random integers between 0 to 50
x = np.random.randint(0,50,1000)

# Negative Correlation with some noise
y = 100 - x + np.random.normal(0,5,1000)

np.corrcoef(x,y)

plt.scatter(x,y)
plt.show()