# -*- coding: utf-8 -*-
"""8C No/Weak Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPnnFPtssOnhdJAOLIVsjeFGZYHgYNbW
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

np.random.seed(1)

# 1000 random integers between 0 to 50
x = np.random.randint(0,50,1000)

# No/Weak Correlation with some noise
y = np.random.randint(0,50,1000)

np.corrcoef(x,y)

plt.scatter(x,y)
plt.show()