# -*- coding: utf-8 -*-
"""1A. Descriptive Statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCjvxj8YgAjtutS0Z9br1zkDaqR25D3l
"""

import pandas as pd

# Create a dictionary of series

d = {'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]), 'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])}

# Create a DataFrame

df = pd.DataFrame(d)

print(df)

# Printing the Sum
print(df.sum())

# Printing the Mean
print(df.mean())

# Printing the Standard Deviation
print(df.std())

# Printing the Descriptive Statistics
print(df.describe())