# -*- coding: utf-8 -*-
"""3A Hypothesis Sample T-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VlOzFvSM02PwB1xwetnjb-tMHKTMsVLn
"""

from scipy.stats import ttest_1samp

import numpy as np

ages = np.genfromtxt("ages.csv")

print(ages)

ages_mean = np.mean(ages)
print(ages_mean)

tset, pval = ttest_1samp(ages,30)
print('p-value :',pval)

if pval < 0.05:  # alpha value is 0.05
  print("We are rejecting null hypothesis")
else:
  print("We are accepting null hypothesis")