# -*- coding: utf-8 -*-
"""5B Two Sample Z-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uvM5neZSFZpNuYNmIqevA0p_DDDWbBHE
"""

import pandas as pd
from statsmodels.stats import weightstats as stests

# Uploading and Importing the "blood_pressure.csv" file
df = pd.read_csv("C:/Users/VivekN7/Desktop/MU Practical/RIC Practical/5 - Z-Test/Support Files/blood_pressure.csv")

df[['bp_before', 'bp_after']].describe()
print(df)

ztest, pval = stests.ztest(df['bp_before'], x2 = df['bp_after'], value = 0, alternative = "two-sided")
print(float(pval))

if pval < 0.05:
  print("Reject Null Hypothesis")
else:
  print("Accept Null Hypothesis")
